/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./ui/**/*.html"],
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#160066",
        "on-secondary": "#28069c",
        "surface-container": "#1d1f28",
        "surface-variant": "#33343d",
        "primary": "#c6bfff",
        "on-primary": "#2900a0",
        "status-error": "#EF4444",
        "text-secondary": "#8A8F9C",
        "inverse-primary": "#5847d2",
        "inverse-surface": "#e1e1ed",
        "tertiary-container": "#ac5d00",
        "on-error": "#690005",
        "outline-variant": "#474554",
        "status-success": "#4ADE80",
        "primary-fixed-dim": "#c6bfff",
        "on-surface-variant": "#c8c4d7",
        "surface-elevated": "#20232F",
        "on-surface": "#e1e1ed",
        "secondary-fixed-dim": "#c6bfff",
        "background": "#11131b",
        "primary-fixed": "#e4dfff",
        "secondary-fixed": "#e4dfff",
        "inverse-on-surface": "#2e3039",
        "on-tertiary-fixed": "#2f1500",
        "tertiary-fixed": "#ffdcc3",
        "outline": "#928ea0",
        "on-primary-fixed": "#160066",
        "surface-card": "#1B1E29",
        "on-background": "#e1e1ed",
        "text-primary": "#FFFFFF",
        "on-tertiary": "#4d2600",
        "primary-container": "#6c5ce7",
        "surface": "#11131b",
        "on-primary-fixed-variant": "#4029ba",
        "surface-container-high": "#282a32",
        "on-primary-container": "#faf6ff",
        "secondary": "#c6bfff",
        "tertiary": "#ffb77d",
        "status-warning": "#F59E0B",
        "surface-dim": "#11131b",
        "error-container": "#93000a",
        "surface-container-low": "#191b23",
        "on-tertiary-container": "#fff5f1",
        "on-secondary-container": "#b7afff",
        "error": "#ffb4ab",
        "tertiary-fixed-dim": "#ffb77d",
        "surface-tint": "#c6bfff",
        "on-error-container": "#ffdad6",
        "surface-container-lowest": "#0c0e16",
        "surface-bright": "#373942",
        "on-secondary-fixed-variant": "#402eb1",
        "secondary-container": "#4331b4",
        "on-tertiary-fixed-variant": "#6e3900",
        "surface-container-highest": "#33343d",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "list-gap": "8px",
        "sidebar-width": "240px",
        "card-padding": "16px",
        "detail-panel-width": "320px",
        "container-margin": "24px",
        "gutter": "16px",
      },
      fontFamily: {
        "body-md": ["Inter"],
        "label-sm": ["Inter"],
        "body-sm": ["Inter"],
        "body-lg": ["Inter"],
        "label-md": ["Inter"],
        "headline-lg": ["Inter"],
        "headline-md": ["Inter"],
      },
    },
  },
  plugins: [],
};
